### ISSUE TITLE
Add from adjacency matrices to nvd object function

### ISSUE THREAD

**Issue by danielemule** [astamm/nevada#13]
This function should create an `nvd` object from a list of adjacency matrices.

**Comment by astamm** [comment]
Don't think it is necessary. **igraph** already have all sorts of `graph_from_*()` functions (including `graph_from_adjacency_matrix()`) which handles this.

So I would suggest that the user makes use of these functions first. That way, (s)he controls whether the graph should be directed or not, include loops or not and so on.

Then, once a list of igraph objects is available, `as_nvd()` should do the trick.
