### ISSUE TITLE
Sampling networks from Binomial and Poisson distribution

### ISSUE THREAD

**Issue by danielemule** [astamm/nevada#5]
`nvd` function fails to sample networks from Binomial and Poisson distribution.
As we can see from [the definition of the nvd function](https://github.com/astamm/nevada/blob/master/R/nvd-class.R), at [line 57](https://github.com/astamm/nevada/blob/c5f31110f3235dc6043567f16ffc2af3a95da44d/R/nvd-class.R#L57), `rpois_network` function is used, but the number of nodes (25 in this case) is assigned to the argument `n`, instead of `num_vertices`.
Analogously, this happens also for `rbinom_network`.

**Comment by astamm** [comment]
@danielemule can you test the version in #9 if the new `nvd()` is fixed and more useful now?

**Comment by danielemule** [comment]
@astamm the version in #9 solves issues #5 and #6; the new `nvd()` is more useful and more customizable.
